# Generated by Django 2.1.8 on 2019-05-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190525_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='option',
            field=models.TextField(null=True),
        ),
    ]
