# Generated by Django 2.1.8 on 2019-05-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
