# Generated by Django 2.1.8 on 2019-05-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20190527_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='timer',
        ),
    ]
