# Generated by Django 2.1.8 on 2019-05-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
