# Generated by Django 2.1.8 on 2019-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='option',
            field=models.TextField(null=True),
        ),
    ]
