# Generated by Django 2.1.8 on 2019-05-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20190520_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='stores.Menu'),
        ),
    ]
