# Generated by Django 2.1.8 on 2019-05-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_order_timer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
