# Generated by Django 2.1.8 on 2019-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20190527_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
