# Generated by Django 2.1.8 on 2019-05-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_auto_20190527_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timer',
            field=models.BooleanField(null=True),
        ),
    ]
