# Generated by Django 2.1.8 on 2019-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_auto_20190527_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timer',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], max_length=50, null=True),
        ),
    ]
