# Generated by Django 2.1.8 on 2019-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_auto_20190528_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
