# Generated by Django 2.1.8 on 2019-05-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20190528_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='timer',
        ),
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], max_length=50, null=True),
        ),
    ]
