# Generated by Django 2.1.8 on 2019-05-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_auto_20190528_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='progress',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], max_length=50, null=True),
        ),
    ]
